var countries = {
    
    "AMS": "Amsterdam",
    "BRN": "Bern",
    "BSB": "Brasilia",
    "BOS": "Boston",
    "BUD": "Budapest",
    "BUH": "Bucharest",
    "BUE": "Buenos Aires",
    "PUS": "Busan",
    "CCS": "Caracas",
    "CHI": "Chicago",

    "DFW": "Dallas",
    "DTW": "Detroit",
    "DUB": "Dublin",

    "EDI": "Edinburgh",

    "HNL": "Hawaii",
    "KIN": "Kingston",
    "HAV": "La Habana",
    "LON": "London",

    "LAS": "Las Vegas",
    "LAX": "Los Angeles",
    
    "MEX": "Mexico City",

    "EWR": "Newark",
    "NYC": "New York",

    "YOW": "Ottawa",
    "PTY": "Panama City",

    "SFO": "San Francisco",
    "SJO": "San Jose",
    "SCL": "Santiago",

    "SAO": "Saopaulo",
    "SEA": "Seattle",
    "BOG": "Sta.Fe De Bogota",

    "YTO": "Toronto",
    "YVR": "Vancouver",
    "WAS": "Washington",     
    
    
    "MAN": "Manchester",
    "BFS": "Belfast",
    "BRU": "Brussels",
    "VIE": "Vienna",
    "CPH": "Cobenhagen",
    "PAR": "Paris",
    "MRS": "Marseille",
    "LYS": "Lyon",
    "NCE": "Nice",
    "WAW": "Warsaw",
    "PRG": "Prague",
    
    "ZRH": "Zurich",
    "GVA": "Geneva",
    "STO": "Stockholm",
    "OSL": "Oslo",
    "HEL": "Helsinki",
    "BER": "Berlin",
    "MUC": "Munich",
    "HAJ": "Hanover",
    "DUS": "Dusseldorf",
    "FRA": "Frankfurt",
    "MAD": "Madrid",
    "BCN": "Barcelona",
    "LIS": "Lisbon",
    "ROM": "Rome",
    "VCE": "Venice",
    "ATH": "Athens",
    "IEV": "Kiev",
    "MOW": "Moscow",
    "SIN": "Changi",
    "BKK": "Bangkok",
    "HKT": "Phuket",
    "HAN": "Hanoi",
    "SGN": "Hochiminh",
    "KUL": "Kuala Lumpur",
    "PEN": "Penang",
    "BKI": "Sabah",
    "JKT": "Jakarta",
    "DPS": "Bali",
    "SUB": "Subaraya",
    "BWN": "Seri Bagawan",
    "MNL": "Manila",
    "CEB": "Cebu",
    "PNH": "Phnum Penh",
    "TYO": "Tokyo",
    "OSA": "Osaka",
    "NGO": "Nagoya",
    "SPK": "Sapporo",
    "SEL": "Seoul",
   
    "DEL": "New Delhi",
    "BOM": "Mumbai",
    "CCU": "Kolkata",
    "BLR": "Bangalore",
    "MAA": "Chennai",
    "ISB": "Islamabad",
    "KHI": "Karchi",
    "DAC": "Dhaka",
    "KTM": "Kathmandu",
    "THR": "Tehran",
    "DOH": "Doha",
    "AUH": "Abu Dhabi",
    "DXB": "Dubai",
    "RUH": "Riyadh",
    "JED": "Jeddah",
    "BAH": "Bahrain",
    "IST": "Istanbul",
    "CBR": "Canberra",
    "SYD": "Sydney",
    "MEL": "Melboruene",
    "PER": "Perth",
    "BNE": "Brisbane",
    "ADL": "Adelaide",
    "WLG": "Wellington",
    "AKL": "Auchland",
    "CAI": "Cairo",
    "JNB": "Johannesburg",
    "CPT": "Capetown",
    "ABV": "Abuja",
    "LOS": "Lagos",
    "NBO": "Nairobi",
    "ADD": "Addis Ababa",
    "HKG": "Hongkong",
    "TPE": "Taibei",
    "KHH": "Kaohsiung",
    "FNJ": "Pyongyang",
    "CKG": "Chongqing",
    "CTU": "Chengdu",
    "CAN": "Guangzhou",
    "HET": "Hohhot",
    "MFM": "Macau",
    "NKG": "Nanjing",
    "SHA": "Shanghai Pudong",
    "PVG": "Shanghai Hongqiao",
    "WUH": "Wuhan",
    "PEK": "Beijing"
    
}